In [14]:
import numpy as np

In [5]:
#1
a = np.array([[1,2,3],
              [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [6]:
#converting to 1D
b = a.reshape(6,)
print(b)

[1 2 3 4 5 6]


In [16]:
#2
c =np.array([[1,2,3],
      [4,5,6],
      [7,8,9]])
print(c.flatten())


[1 2 3 4 5 6 7 8 9]


In [22]:
#3
a = np.array([[[1,2],
               [3,4]],

               [[5,6],
               [7,8]]])
print(a)
print(a.flatten())


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]


In [23]:
#4
a = np.array([[1,2,3],
              [4,5,6]])
print(a.shape)
b = a.flatten()
print(b.shape)

(2, 3)
(6,)


In [24]:
#5
a = np.array([[10,20],
              [30,40],
              [50,60]])
print(a.flatten())

[10 20 30 40 50 60]


In [26]:
#6
q = np.array([1,2,3,4,5,6,7,8])
b = q.reshape(1,4,2)
print(b)
c = q.reshape(2,4)
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
[[1 2 3 4]
 [5 6 7 8]]


Mathematical operations

In [36]:
a = np.array([2,4,6])
b = np.array([1,3,5])
c =np.add(a,b)
print(c)
d = np.subtract(a,b)
print(d)
e = np.multiply(a,b)
print(e)
f = np.divide(a,b)
print(f)
g = np.dot(a,b)
print(g)

[ 3  7 11]
[1 1 1]
[ 2 12 30]
[2.         1.33333333 1.2       ]
44


Aggregate functions

In [37]:
a =np.array([12,5,30,18,9])
a.max()

np.int64(30)

In [38]:
a.min()

np.int64(5)

In [39]:
c =np.sum(a)
print(c)

74


In [40]:
d =np.mean(a)
print(d)

14.8


In [41]:
a.argmax()

np.int64(2)

In [42]:
a.argmin()

np.int64(1)

Axis operations

In [44]:
a=np.array([[1,2,3],
            [4,5,6]])
a.max(axis =0)

array([4, 5, 6])

In [45]:
a.max(axis = 1)

array([3, 6])

In [47]:
a.min(axis =0)

array([1, 2, 3])

In [48]:
a.min(axis =1)

array([1, 4])

In [49]:
a.sum(axis =0)

array([5, 7, 9])

In [50]:
a.sum(axis = 1)

array([ 6, 15])

1D indexing and slicing

In [51]:
a =np.array([5,10,15,20,25,30])
a[0]

np.int64(5)

In [52]:
a[5]

np.int64(30)

In [53]:
a[1:5]

array([10, 15, 20, 25])

In [55]:
a[0:4]

array([ 5, 10, 15, 20])

In [57]:
a[1:6:2]

array([10, 20, 30])

In [59]:
a[::-1]

array([30, 25, 20, 15, 10,  5])

2D indexing and slicing

In [61]:
a =np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
a[1,2]

np.int64(6)

In [62]:
a[0]

array([1, 2, 3])

In [63]:
a[:,1]

array([2, 5, 8])

In [64]:
a[2]

array([7, 8, 9])

In [65]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
a[1:3,1:3]

array([[5, 6],
       [8, 9]])

3D indexing 

In [67]:
a =np.array([[[1,2,3],
              [4,5,6]],

             [[7,8,9],
              [10,11,12]]])
a[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
a[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [73]:
a[0,0]

array([1, 2, 3])

In [74]:
a[1,1]

array([10, 11, 12])

In [75]:
a[1,1,1]

np.int64(11)

In [76]:
a[-1,-1,-1]

np.int64(12)

3D slicing

In [77]:
a[0,0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
a[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [80]:
a[:,0:2,1:2]

array([[[ 2],
        [ 5]],

       [[ 8],
        [11]]])

In [81]:
a[:,:,1:3]

array([[[ 2,  3],
        [ 5,  6]],

       [[ 8,  9],
        [11, 12]]])

In [82]:
a[:,:,0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [83]:
a[:,:,::-1]

array([[[ 3,  2,  1],
        [ 6,  5,  4]],

       [[ 9,  8,  7],
        [12, 11, 10]]])

submatrix operations

In [84]:
a =np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12],
             [13,14,15,16]])
a[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [85]:
a[0:2,2:4]

array([[3, 4],
       [7, 8]])

In [86]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [87]:
a[2:4,2:4]

array([[11, 12],
       [15, 16]])

In [88]:
a[1:3,0:3]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [89]:
a[0:3,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [90]:
a[2:3,:]

array([[ 9, 10, 11, 12]])

In [92]:
a[:,3:4]

array([[ 4],
       [ 8],
       [12],
       [16]])

In [93]:
a[0:3:2,0:3:2]

array([[ 1,  3],
       [ 9, 11]])

In [94]:
a[1:4,1:4]

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])