In [ ]:
# NumPy is an open source python libarary that's widely used in engineering and science. It was created in 2005 by Travis Oliphant.
# Numerical Python(NumPy) is a library that provides support for large,multi-dimensional arrays and matrices , along with a collection 
# of mathematical functions to operate on arrays.

# Features

# N-dimensional array
# Mathematical functions-Operations on arrays
# Integration with other Libraries
# Random number generation 

# Advantages

# Faster than python lists
# Supports multi-dimensional arrays
# Provides a lot of supporting functions
# Memory efficient 

In [ ]:
# Numpy arrays are stored at one continuous place in memory, so processes can access and manipulate them very efficiently.
# Homogeneous data type : No need for data type checking 
# Memory efficiency : NumPy arrays use a more compact representation, leading to lower memory consumption compared to lists.

In [ ]:
# ndim : Number of dimensions of the array
# shape : size of array in each dimension (tuple)
# size : Total no of elements in the array
# dtype : Data type of array elements
# type() : type of the object 

In [ ]:
# a) Python lists - It can store different data types like int,float,string etc. Slower for numerical operations and Uses more memory 
# NumPy array - Stores elements of the same data type. Faster for numerical operations and more memory efficient.

# b) Shpae - Gives the dimensions of array as a tuple
#    size - Gives the total number of elements (integer)

# c) dtype - Returns data type of array elements 
#    type() - Returns the type of the object

In [ ]:
# a represents the layer , b represents rows and c represents columns.

In [3]:
import numpy as np 
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(type(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)
12
int64
<class 'numpy.ndarray'>


In [5]:
b = np.array([
    [9,8,7],
    [5,6,7],
    [1,2,3],
    [4,5,6],
    [9,2,1],
    [5,3,8]
]
            )
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(type(b))

[[9 8 7]
 [5 6 7]
 [1 2 3]
 [4 5 6]
 [9 2 1]
 [5 3 8]]
2
(6, 3)
18
int64
<class 'numpy.ndarray'>


In [9]:
c = np.array([
    [[1,2],
     [3,4],
     [5,6],
     [9,8]],

    [[2,2],
     [4,4],
     [6,6],
     [2,8]],

    [[6,6],
        [1,1],
        [0,9],
        [6,6]]
]
            )

print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(type(c))     
    

[[[1 2]
  [3 4]
  [5 6]
  [9 8]]

 [[2 2]
  [4 4]
  [6 6]
  [2 8]]

 [[6 6]
  [1 1]
  [0 9]
  [6 6]]]
3
(3, 4, 2)
24
int64
<class 'numpy.ndarray'>


In [11]:
d = np.array([
[[1,2,3,4,5,6],
    [9,8,7,5,4,3],
    [1,0,9,8,3,8],
    [9,6,5,7,4,2]],

[[10,11,12,13,14,15],
 [9,3,1,5,7,8],
 [15,16,17,8,19,20],
 [2,3,4,5,6,7]]
]
            )

print(d)
print(d.ndim)
print(d.shape)
print(d.size)
print(d.dtype)   
    
    

[[[ 1  2  3  4  5  6]
  [ 9  8  7  5  4  3]
  [ 1  0  9  8  3  8]
  [ 9  6  5  7  4  2]]

 [[10 11 12 13 14 15]
  [ 9  3  1  5  7  8]
  [15 16 17  8 19 20]
  [ 2  3  4  5  6  7]]]
3
(2, 4, 6)
48
int64
