In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(arr + 5)
print(arr * 2)

[6 7 8]
[2 4 6]


Beoadcasting (automatic expansion of dimensions)

In [4]:
matrix = np.array([[1,2],[3,4]])
vector = np.array([5,6])
print(matrix + vector )

[[ 6  8]
 [ 8 10]]


array creation

In [5]:
np.zeros((2,3,6),dtype='int') #2*3 matrix of zeros

array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]])

In [6]:
np.ones((3,3,3)) #3*3 matrix of ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
np.eye(5,3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.arange(0,101,2) #even numbers fro  0 to 100

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [12]:
np.linspace(0,1,10) #evenly spaced btw 0 and 1 #deafult 50

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

boolean operations

In [14]:
arr = np.array([1,2,3,4,5])
b = arr > 2
print(b)
print(arr[b])

[False False  True  True  True]
[3 4 5]


In [15]:
#odd numbers are replaced with -1, even numbers remain unchanged
arr = np.array([1,2,3,4,5,])
new_arr = np.where(arr % 2 ==0, arr , -1)
print(new_arr)

[-1  2 -1  4 -1]


aggregate function

In [17]:
matrix = np.array([[1,2],[3,4]])
print(np.mean(matrix))
print(np.max(matrix))
print(np.sum(matrix))

2.5
4
10


In [18]:
#diagonal elements
a = np.diag([3,34,9,99])
a

array([[ 3,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 99]])

In [20]:
a =np.random.random((2,3))
a

array([[0.09943277, 0.88523331, 0.65254666],
       [0.77389808, 0.86304728, 0.97268159]])

In [22]:
np.random.seed(2)
a = np.random.random((2,))
print(a)

[0.4359949  0.02592623]


In [28]:
a = np.random.randint(1,21,(2,3))
a

array([[12, 19, 12],
       [ 9,  8,  3]], dtype=int32)