In [1]:
import numpy as np

In [2]:
#covert from 1d to other d (reshape)
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [4]:
#1D to 2D
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3) #(1,6)(6,1)(3,2)
print(a)
print(b)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [5]:
#1D to 3D
c = np.array([1,2,3,4,5,6])
d = c.reshape(1,2,3)
print(d)

[[[1 2 3]
  [4 5 6]]]


In [6]:
#2D to 1D
a = np.array([[1,2],[3,4],[6,7],[9,8]])#(4,2)
e = a.reshape(8,)
print(e)

[1 2 3 4 6 7 9 8]


In [7]:
#2D to 3D
b = np.array([[1,2],[3,4],[5,6],[7,8]])
d = b.reshape(1,4,2)
print(d)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [10]:
#3D to 2D
p = np.array([[[9,9],[5,5],[4,4],[2,2]]])
s = p.reshape(4,2)
print(s)

[[9 9]
 [5 5]
 [4 4]
 [2 2]]


In [11]:
#3D to 1D
q = np.array([[[9,9],[5,5],[1,1],[0,0]]])
l = q.reshape(8,)
print(l)

[9 9 5 5 1 1 0 0]


In [12]:
q = np.array([[[9,9],[5,5],[1,1],[0,0]]])
print(q)

[[[9 9]
  [5 5]
  [1 1]
  [0 0]]]


In [15]:
#covert any D to 1D
q.flatten()

array([9, 9, 5, 5, 1, 1, 0, 0])

In [14]:
q.reshape(-1)

array([9, 9, 5, 5, 1, 1, 0, 0])

In [17]:
#mathematical optns
a = np.array([1,2])
b = np.array([7,8])
c= np.add(a,b)
print(c)

[ 8 10]


In [23]:
c = np.dot(a,b)
print(c)

23


In [19]:
c = np.subtract(a,b)
c

array([-6, -6])

In [21]:
c = np.multiply(a,b)
c

array([ 7, 16])

In [24]:
a = np.array([10,8,99,2])
a.max()

np.int64(99)

In [25]:
a.min()

np.int64(2)

In [26]:
a.argmax()

np.int64(2)

In [27]:
a.argmin()

np.int64(3)

In [28]:
a.max(axis = 0)

np.int64(99)

In [30]:
a.min(axis = 0)

np.int64(2)

In [31]:
a.argmax(axis = 0)

np.int64(2)

In [32]:
a.argmin(axis = 0)

np.int64(3)

In [33]:
m =np.array([5,6,7,3])
m

array([5, 6, 7, 3])

In [35]:
k = m.copy()
k

array([5, 6, 7, 3])

In [36]:
k[1] = 88
k

array([ 5, 88,  7,  3])

In [37]:
m

array([5, 6, 7, 3])

In [42]:
#indexing 1D
a = np.array([5,6,7,8])
a[0]

np.int64(5)

In [39]:
a[-2]

np.int64(7)

In [40]:
a[0:2]

array([5, 6])

In [41]:
a[-3:-1]

array([6, 7])

In [44]:
#indexing 2D
a = np.array([
    [1,2],
    [5,6]
])
a

array([[1, 2],
       [5, 6]])

In [45]:
a[0,1]

np.int64(2)

In [46]:
a[-2,-1]

np.int64(2)

In [47]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
a[1,1]

np.int64(5)

In [49]:
a[-1,-3]

np.int64(4)

In [54]:
s =np.array([[[1,2,3],
             [4,5,6]],
             
             [[7,8,9],
             [10,11,12]],

             [[13,14,15],
            [16,17,18]]
            ])
s

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [55]:
s[1,0,1]

np.int64(8)

In [56]:
s[-1,-2,-1]

np.int64(15)

In [57]:
s[0,0:2,1:3]

array([[2, 3],
       [5, 6]])

In [58]:
c =np.array(
    [ 
        [1,2,3,4],
        [6,7,8,9],
        [0,3,5,6]
    ]
)
c

array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [0, 3, 5, 6]])

In [59]:
c[1:3,1:3]

array([[7, 8],
       [3, 5]])

In [61]:
c[0:3,0:2]

array([[1, 2],
       [6, 7],
       [0, 3]])